import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import SessionProvider from "@/providers/session";
import { ModeProvider } from "@/providers/mode";
import { cn } from "@/lib/utils";
import ThemeWrapper from "@/components/theme/wrapper";
import { Toaster } from "@/components/ui/toaster";
import EncryptionProvider from "@/providers/encryption";
import { Provider } from "jotai";
import JotaiProvider from "@/providers/jotai";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(GeistSans.className, "theme-zinc")}>
        <JotaiProvider>
          <TooltipProvider>
            <ModeProvider attribute="class" defaultTheme="system" enableSystem>
              <ThemeWrapper defaultTheme="zinc">
                <SessionProvider>
                  {children}
                  <Toaster />
                </SessionProvider>
              </ThemeWrapper>
            </ModeProvider>
          </TooltipProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
